// Fetch Google Fonts (Source Serif 4, Inter Tight, JetBrains Mono) and bundle the woff2
// files + a fonts.css shim under src/renderer/src/assets/fonts/. The fonts are committed so
// the app stays offline-first - never fetches Google Fonts at runtime. Re-run only when the
// upstream font files change (Google publishes new versions).
//
// Usage:  node scripts/fetch-fonts.mjs
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '..', 'src/renderer/src/assets/fonts')
mkdirSync(OUT, { recursive: true })

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Gecko/20100101 Firefox/120.0'
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Source+Serif+4:opsz,wght@8..60,300;8..60,400;8..60,500;8..60,600;8..60,700' +
  '&family=Inter+Tight:wght@400;500;600;700' +
  '&family=JetBrains+Mono:wght@400;500' +
  '&display=swap'

console.log('fetching css:', CSS_URL)
const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => r.text())

// Pre-scan: collect (comment-subset, @font-face) pairs in document order so each face
// can borrow the subset label from its preceding /* latin */-style comment.
const pairs = []
const re = /\/\*\s*\[?([a-z0-9-]+)\]?\s*\*\/\s*(@font-face\s*\{[^}]+\})/gi
let m
while ((m = re.exec(css)) !== null) pairs.push({ subset: m[1], block: m[2] })
console.log(`parsed ${pairs.length} @font-face declarations`)

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

const cssOut = []
let downloaded = 0
for (const { subset, block } of pairs) {
  const family = (/font-family:\s*'([^']+)'/.exec(block) || [])[1] || 'font'
  const weight = (/font-weight:\s*([^;]+);/.exec(block) || [])[1].trim() || '400'
  const style = (/font-style:\s*([^;]+);/.exec(block) || [])[1].trim() || 'normal'
  const url = (/url\((https:[^)]+)\)/.exec(block) || [])[1]
  if (!url) continue
  const ext = url.endsWith('.woff2') ? 'woff2' : url.endsWith('.woff') ? 'woff' : 'ttf'
  const w = weight.replace(/\s+/g, '_')
  const name = `${slug(family)}-${w}-${style}-${subset}.${ext}`
  console.log('->', name)
  const bin = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.arrayBuffer())
  writeFileSync(resolve(OUT, name), Buffer.from(bin))
  downloaded++
  cssOut.push(block.replace(/url\(https:[^)]+\)/, `url('./${name}')`).trim())
}

const finalCss =
  '/* Auto-generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n' +
  cssOut.join('\n\n') +
  '\n'
writeFileSync(resolve(OUT, 'fonts.css'), finalCss)
console.log(`wrote ${OUT}/fonts.css with ${downloaded} faces`)
